name: Deploy backend to host
'on' :
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      -
        name: run maven
        run: |
            mvn clean install -DskipTests -B
            mkdir -p target/dependency && (cd target/dependency; unzip ../*.jar)
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
